on:
  schedule:
    - cron: "*/5 * * * *"

env:
  GIT_AUTHOR_NAME: aryehky
  GIT_AUTHOR_EMAIL: kyky0112@gmail.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make random changes to README.md
      run: |
        rand=$(shuf -i 1-2 -n 1)
        if [ $rand -eq 1 ]; then
          echo "." >> README.md
          git add README.md
          git commit -m "Made random changes to README"
          git push origin HEAD
        else
          echo "No changes made."
        fi
