name: Scheduled Pull Request

on:
  schedule:
    - cron: "0 */36 * * *" # Runs every 36 hours

env:
  GIT_AUTHOR_NAME: aryehky
  GIT_AUTHOR_EMAIL: kyky0112@gmail.com

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.email "$GIT_AUTHOR_EMAIL"
        git config --global user.name "$GIT_AUTHOR_NAME"

    - name: Randomly decide to make changes
      run: |
        rand=$(shuf -i 1-2 -n 1)
        if [ $rand -eq 1 ]; then
          echo "." >> README.md
        else
          echo "No changes made."
        fi

    - name: Commit changes
      run: |
        if [[ -n $(git status -s) ]]; then
          git checkout -b automated-changes
          git add .
          git commit -m "Automated updates on $(date)"
          git push origin automated-changes
        else
          echo "No changes to commit."
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: automated-changes
        base: main
        title: "Automated Updates: $(date)"
        body: |
          This pull request includes automated updates made by the scheduled workflow.
